<?xml version="1.0" encoding="utf-8"?><Database Name="Eventor_Project.Models.CurrentContext" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\Eventor_Project.Models.CurrentContext.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Eventor_Project_Models_CurrentContextConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Benefits" Member="Benefits">
    <Type Name="Benefits">
      <Column Name="BenefitId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Benefits_BenefitUsers" Member="BenefitUsers" ThisKey="BenefitId" OtherKey="Benefit_BenefitId" Type="BenefitUsers" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="Users">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Nickname" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Surname" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Patronymic" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Sex" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PlaceOfStudy_PlaceId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PlaceOfLiving_PlaceId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ContactEmail" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Users_BenefitUsers" Member="BenefitUsers" ThisKey="UserId" OtherKey="User_UserId" Type="BenefitUsers" />
      <Association Name="Users_RoleUsers" Member="RoleUsers" ThisKey="UserId" OtherKey="User_UserId" Type="RoleUsers" />
      <Association Name="Places_Users" Member="Places" ThisKey="PlaceOfLiving_PlaceId" OtherKey="PlaceId" Type="Places" IsForeignKey="true" />
      <Association Name="Places_Users1" Member="Places1" ThisKey="PlaceOfStudy_PlaceId" OtherKey="PlaceId" Type="Places" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BenefitUsers" Member="BenefitUsers">
    <Type Name="BenefitUsers">
      <Column Name="Benefit_BenefitId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="User_UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Benefits_BenefitUsers" Member="Benefits" ThisKey="Benefit_BenefitId" OtherKey="BenefitId" Type="Benefits" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Users_BenefitUsers" Member="Users" ThisKey="User_UserId" OtherKey="UserId" Type="Users" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Places" Member="Places">
    <Type Name="Places">
      <Column Name="PlaceId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PlaceInfo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Places_Users" Member="Users" ThisKey="PlaceId" OtherKey="PlaceOfLiving_PlaceId" Type="Users" />
      <Association Name="Places_Users1" Member="Users1" ThisKey="PlaceId" OtherKey="PlaceOfStudy_PlaceId" Type="Users" />
    </Type>
  </Table>
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Roles">
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Roles_RoleUsers" Member="RoleUsers" ThisKey="RoleId" OtherKey="Role_RoleId" Type="RoleUsers" />
    </Type>
  </Table>
  <Table Name="dbo.RoleUsers" Member="RoleUsers">
    <Type Name="RoleUsers">
      <Column Name="Role_RoleId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="User_UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Roles_RoleUsers" Member="Roles" ThisKey="Role_RoleId" OtherKey="RoleId" Type="Roles" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Users_RoleUsers" Member="Users" ThisKey="User_UserId" OtherKey="UserId" Type="Users" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
</Database>