// <auto-generated />
namespace Eventor_Project.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class nullable_categotyid_projectmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nullable_categotyid_projectmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201510080724340_nullable_categotyid_projectmodel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
