// <auto-generated />
namespace Eventor_Project.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddRequiredCount_Organizer_Project : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRequiredCount_Organizer_Project));
        
        string IMigrationMetadata.Id
        {
            get { return "201510121522371_AddRequiredCount_Organizer_Project"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
