// <auto-generated />
namespace Eventor_Project.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Remove_Requried_Fields_In_ProjectModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Remove_Requried_Fields_In_ProjectModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201510080647328_Remove_Requried_Fields_In_ProjectModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
