// <auto-generated />
namespace Eventor_Project.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class message3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(message3));
        
        string IMigrationMetadata.Id
        {
            get { return "201511021627042_message3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
