// <auto-generated />
namespace Eventor_Project.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _123123 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_123123));
        
        string IMigrationMetadata.Id
        {
            get { return "201511161919380_123123"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
