// <auto-generated />
namespace Eventor_Project.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Add_EF_DataAnnotains : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_EF_DataAnnotains));
        
        string IMigrationMetadata.Id
        {
            get { return "201509212039350_Add_EF_DataAnnotains"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
